automation:
  - id: unifi_protect_vehicle_detected_doorbell
    alias: Send message when vehicle detected doorbell
    mode: single
    
    description: >
      record and send a video when vehicle seen
      
    trigger:
      - platform: state
        id: 'vehicle'
        entity_id:  sensor.doorbell_detected_object
        to: vehicle
        
    variables:
      pic_file: "{{ 'doorbell_' + now().strftime('%d%m%H%M') }}"    
      pic_folder: "/config/www/cam_snaps/"      
      base_url: !secret base_url
      
    action:
      - alias: "send photo by telegram"        
        service: telegram_bot.send_photo
        data:
          caption: "I have seen a vehicle on the doorbell camera."
          url: "{{ base_url + state_attr('sensor.doorbell_detected_object','event_thumbnail') }}"
          message_tag: object_detected_doorbell                  
          target: !secret telegram_chat_id_bruce
          
      - alias: "record camera to mp4"           
        service: camera.record
        target:
          entity_id: camera.doorbell_medium       
        data:
          duration: 10
          filename: "{{ pic_folder + pic_file }}.mp4"  
          
      - alias: "Wait for Event to End"
        wait_for_trigger:
          - platform: state
            entity_id: sensor.doorbell_detected_object
            to: "none"

      - alias: "delete Telegram message"              
        service: telegram_bot.delete_message
        data:
          message_id: "{{ states('input_text.object_detected_doorbell_message_id') }}"
          chat_id: !secret telegram_chat_id_bruce  
          
      - alias: "send photo by telegram"             
        service: telegram_bot.send_photo
        data:
          caption: "I have seen a vehicle on the doorbell camera."
          url: "{{ base_url + wait.trigger.from_state.attributes.event_thumbnail }}"
          message_tag: object_detected_doorbell                  
          target: !secret telegram_chat_id_bruce
          
      - alias: "download vehicle image"
        service: downloader.download_file
        data:
          url: "{{ base_url + wait.trigger.from_state.attributes.event_thumbnail }}"
          filename: "{{ pic_folder + pic_file }}.jpg"
          overwrite: true
          
      - alias: "Wait for image to download"
        wait_for_trigger:
          - platform: event
            event_type: downloader_download_completed

      - alias: "update camera to use new image"
        service: local_file.update_file_path
        target:
          entity_id: camera.latest_car
        data:
          file_path: "{{ pic_folder + pic_file }}.jpg"        
          
      - alias: "trigger plate recognizer"
        service: image_processing.scan
        target:
          entity_id: image_processing.latest_car

      - alias: "wait for video file to be written"            
        wait_template: "{{ pic_file in states.sensor.cam_snaps.attributes.file_list }}"
        timeout: '00:00:20'
        
      - alias: "Edit telegram message to add keyboard"          
        service: telegram_bot.edit_caption
        data:
          message_id: "{{ states('input_text.object_detected_doorbell_message_id') }}"
          chat_id: !secret telegram_chat_id_bruce  
          caption: "I have seen a vehicle {{ state_attr('image_processing.platerecognizer_latest_car','vehicles')[0].plate or ''}} on the doorbell camera."
          inline_keyboard:
            - "Video:/vdd {{pic_file}}, OK:/remove_keyboard"                   
