automation:
  - id: unifi_protect_person_detected_patio
    alias: Send message when person detected patio
    mode: single
    
    description: >
      record and send a video when person seen
      
    trigger:
      - platform: state
        id: 'person'
        entity_id:  sensor.patio_detected_object
        to: person
      - platform: state
        id: 'gate'
        entity_id: binary_sensor.back_gate_door
        to: 'on'            
        
    variables:
      pic_file: "{{ 'patio_' + now().strftime('%d%m%H%M') }}"    
      pic_folder: "/config/www/cam_snaps/"      
      base_url: !secret base_url
      
    action:
      - choose:
          - conditions: 
              - condition: trigger
                id: 'person'
            sequence:      
              - alias: "send photo by telegram"               
                service: telegram_bot.send_photo
                data:
                  caption: "I have seen a person on the patio camera."
                  url: "{{ base_url + state_attr('camera.patio_medium','entity_picture') }}" 
 #                 url: "{{ base_url + state_attr('sensor.patio_detected_object','event_thumbnail') }}"
                  message_tag: object_detected_patio                  
                  target: !secret telegram_chat_id_bruce
                  
              - alias: "record camera to mp4"                       
                service: camera.record
                target:
                  entity_id: camera.patio_medium       
                data:
                  duration: 10
                  filename: "{{ pic_folder + pic_file }}.mp4"    
                  
              - alias: "Wait for Event to End"
                wait_for_trigger:
                  - platform: state
                    entity_id: sensor.patio_detected_object
                    to: "none"
                    
              - alias: "delete Telegram message"                        
                service: telegram_bot.delete_message
                data:
                  message_id: "{{ states('input_text.object_detected_patio_message_id') }}"
                  chat_id: !secret telegram_chat_id_bruce   

              - alias: "send photo by telegram"                      
                service: telegram_bot.send_photo
                data:
                  caption: "I have seen a person on the patio camera."
                  url: "{{ base_url + wait.trigger.from_state.attributes.event_thumbnail }}"
                  message_tag: object_detected_patio                  
                  target: !secret telegram_chat_id_bruce        

              - alias: "wait for video file to be written"                    
                wait_template: "{{ pic_file in states.sensor.cam_snaps.attributes.file_list }}"
                timeout: '00:00:20'
                
              - alias: "Edit telegram message to add keyboard"                      
                service: telegram_bot.edit_caption
                data:
                  message_id: "{{ states('input_text.object_detected_patio_message_id') }}"
                  chat_id: !secret telegram_chat_id_bruce   
                  caption: "I have seen a person on the patio camera."
                  inline_keyboard:
                    - "Video:/vdd {{pic_file}}, OK:/remove_keyboard"                   

          - conditions: 
              - condition: trigger
                id: 'gate'
            sequence:      

              - alias: "send photo by telegram"              
                service: telegram_bot.send_photo
                data:
                  caption: "Back Gate Opened"
                  url: "{{ base_url + state_attr('camera.patio_medium','entity_picture') }}"
                  message_tag: object_detected_patio                  
                  target: !secret telegram_chat_id_bruce
                  
              - alias: "record camera to mp4"                      
                service: camera.record
                target:
                  entity_id: camera.patio_medium       
                data:
                  duration: 10
                  filename: "{{ pic_folder + pic_file }}.mp4"    
                  
              - alias: "wait for video file to be written"                       
                wait_template: "{{ pic_file in states.sensor.cam_snaps.attributes.file_list }}"
                timeout: '00:00:20'
                
              - alias: "Edit telegram message to add keyboard"                    
                service: telegram_bot.edit_caption
                data:
                  message_id: "{{ states('input_text.object_detected_patio_message_id') }}"
                  chat_id: !secret telegram_chat_id_bruce  
                  caption: "Back Gate opened"
                  inline_keyboard:
                    - "Video:/vdd {{pic_file}}, OK:/remove_keyboard"                   
              

