automation:
  - id: dimmer_control_utility_lights
    alias: 'Dimmer Control of Utility Lights'
    mode: restart
    
    description: >
      Control utility light from dimmer switch
      
    trigger:
    - platform: event
      id: 'dimmer on'
      event_type: hue_event
      event_data:
        id: "utility_switch"
        event: 1002
    - platform: event
      id: 'dimmer off'
      event_type: hue_event
      event_data:
        id: "utility_switch"
        event: 4000      
    - platform: state
      id: 'light'
      entity_id: light.utility_light
      to: 'off'      
      
    action:
      - choose:
          - conditions: 
              - condition: trigger
                id: 'light'
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.utility_light_manually_on      

          - conditions: 
              - condition: trigger
                id: 'dimmer on'  
            sequence:          
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.utility_light_manually_on

          - conditions: 
              - condition: trigger
                id: 'dimmer off'   
            sequence:          
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.utility_light_manually_on



