ac_start:
  description: Start A/C on vehicle.
  fields:
    vehicle:
      name: Vehicle
      description: The vehicle to send the command to.
      required: true
      selector:
        device:
          integration: renault
    temperature:
      description: Target A/C temperature in °C.
      example: "21"
      required: true
      selector:
        number:
          min: 15
          max: 25
          step: 0.5
          unit_of_measurement: °C
    when:
      description: Timestamp for the start of the A/C (optional - defaults to now).
      example: "2020-05-01T17:45:00"
      selector:
        text:

ac_cancel:
  description: Cancel A/C on vehicle.
  fields:
    vehicle:
      name: Vehicle
      description: The vehicle to send the command to.
      required: true
      selector:
        device:
          integration: renault

charge_set_schedules:
  description: Update charge schedule on vehicle.
  fields:
    vehicle:
      name: Vehicle
      description: The vehicle to send the command to.
      required: true
      selector:
        device:
          integration: renault
    schedules:
      description: Schedule details.
      example: >-
        [
          {
            'id':1,
            'activated':true,
            'monday':{'startTime':'T12:00Z','duration':15},
            'tuesday':{'startTime':'T12:00Z','duration':15},
            'wednesday':{'startTime':'T12:00Z','duration':15},
            'thursday':{'startTime':'T12:00Z','duration':15},
            'friday':{'startTime':'T12:00Z','duration':15},
            'saturday':{'startTime':'T12:00Z','duration':15},
            'sunday':{'startTime':'T12:00Z','duration':15}
          },
          {
            'id':2,
            'activated':false,
            'monday':{'startTime':'T12:00Z','duration':240},
            'tuesday':{'startTime':'T12:00Z','duration':240},
            'wednesday':{'startTime':'T12:00Z','duration':240},
            'thursday':{'startTime':'T12:00Z','duration':240},
            'friday':{'startTime':'T12:00Z','duration':240},
            'saturday':{'startTime':'T12:00Z','duration':240},
            'sunday':{'startTime':'T12:00Z','duration':240}
          },
        ]
      required: true
      selector:
        object:

charge_start:
  description: Start charge on vehicle.
  fields:
    vehicle:
      name: Vehicle
      description: The vehicle to send the command to.
      required: true
      selector:
        device:
          integration: renault
