input_datetime:
    filter_cycle1_begins:
        name: Filter Cycle 1 Begins
        has_date: false
        has_time: true
    filter_cycle1_runs:
        name: Filter Cycle 1 Runs
        has_date: false
        has_time: true
    filter_cycle2_begins:
        name: Filter Cycle 2 Begins
        has_date: false
        has_time: true
    filter_cycle2_runs:
        name: Filter Cycle 2 Runs
        has_date: false
        has_time: true
