automation:
  - id: cupboard_and_worktop_on_when_lights_2_on_first
    alias: 'Turn on cupboard when kitchen 2 lights on first'
    
    description: >
      If Lights switch 2 turned on first, switch on cupboard & worktop
      
    trigger: 
      - platform: state
        id: "ceiling2"
        entity_id: light.kitchen_ceiling_2
        from: 'off'
        to: 'on'
        
    condition:
      - condition: state
        entity_id: 
          - light.kitchen_ceiling_1
          - light.kitchen_ceiling_3
          - light.kitchen_ceiling_4
        state: 'off'
        
    action:
      - service: light.turn_on
        target:
          entity_id: 
            - light.kitchen_cupboard 
            - light.kitchen_worktop