automation:
  - id: purge_recorder_database
    alias: system_recorder_purge
    mode: single
    
    description: >
      Purge recorder database
      
    trigger:
      - platform: time_pattern
        id: "12m"
        minutes: 12
        
    action:
      - service: recorder.purge
