sensor:
  - platform: mqtt_room
    #unique_id: espresence_kate_iphone
    device_id: !secret kate_iphone_ra
    name: 'EsPresence Kate iPhone'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120