automation:
  - id: enable_disable_jyggy_sleep
    alias: Sleep or Wake jyggy
    mode: restart
    
    description: >
      enable disable jyggy sleep

    trigger: 
      - platform: state
        id: "plug"
        entity_id: binary_sensor.zappi_jyggy_plugged_in
      - platform: state
        id: 'charging'
        entity_id: sensor.zappi_jyggy_status
        to: 'Charging'
      - platform: state
        id: 'disconnected'
        entity_id: sensor.zappi_jyggy_status
        to: 'EV Disconnected'


    action:
      - choose:
          - conditions: 
              - condition: trigger
                id: 'charging'
            sequence:
              - service: rest_command.jyggy_api
                data:
                  teslafi_token: !secret teslafi_token                 
                  jyggy_command: "wake"
              - service: logbook.log
                data:
                  domain: sensor
                  entity_id: sensor.jyggy_carstate
                  name: "Jyggy"
                  message: "Waking up for Charging"
                  
          - conditions: 
              - condition: trigger
                id: 'disconnected'
            sequence:
              - service: rest_command.jyggy_api
                data:
                  teslafi_token: !secret teslafi_token                 
                  jyggy_command: "wake"      
              - service: logbook.log
                data:
                  domain: sensor
                  entity_id: sensor.jyggy_carstate
                  name: "Jyggy"
                  message: "Waking up as Unplugged"
                  
        default:
          - service: rest_command.jyggy_api
            data:
              teslafi_token: !secret teslafi_token                 
              jyggy_command: "sleep"    
          - service: logbook.log
            data:
              domain: sensor
              entity_id: sensor.jyggy_carstate
              name: "Jyggy"
              message: "Trying to Sleep"              