automation:
  - id: bar_lights_when_door_opened
    alias: 'Bar Lights on from door'
    mode: restart

    description: >-
      Bar Lights on when door opened
      
    trigger:
      - platform: state
        id: "door"
        entity_id: binary_sensor.bar_door
        from: 'off'
        to: 'on'

    condition:
      - condition: state
        entity_id: binary_sensor.light_outside
        state: 'off'
      - condition: state
        entity_id: light.bar
        state: 'off'

    action:
      - alias: "Bar Lights on from door"
        service: light.turn_on
        target:
          entity_id: 
            - light.bar_bar
            - light.bar_palm
        data:
          brightness: 75
