automation:
  - id: turn_off_lights
    alias: 'Turn off all lights'

    description: >
      Turn off lights from ios notifcation button
        
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: 'all_lights_off'    
      - platform: event
        event_type: ios.notification_action_fired
        event_data:
          actionName: TURN_OFF_LIGHTS
          
    action:
      service: light.turn_off
      target:
        entity_id: light.home