automation:
  - id: lights_on_turn_off_sleep_switches
    alias: 'Turn off sleep switches when lights on'
    mode: queued
    
    description: >
      Lights on, turn off Asleep Switches
      
    trigger:
      - platform: state
        id: "left"
        entity_id: light.master_bedroom_bedside_left
        to: 'on'     
      - platform: state
        id: "right"
        entity_id: light.master_bedroom_bedside_right
        to: 'on'          
      - platform: state
        id: "wall"
        entity_id:
          - light.master_bedroom_wall_left           
          - light.master_bedroom_wall_right          
        to: 'on'   
        
    condition:
      - condition: time
        after: 05:30:00
      - or:
          - condition: state
            entity_id: input_boolean.bruce_is_asleep
            state: 'on'
          - condition: state
            entity_id: input_boolean.sarah_is_asleep
            state: 'on'            
            
    action:
      - choose:
          - conditions: 
              - condition: trigger
                id: "left"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.bruce_is_asleep  

          - conditions:
              - condition: trigger
                id: "right"          
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.sarah_is_asleep  
                  
        default:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.sarah_is_asleep  
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.bruce_is_asleep  