automation:
  - id: wardrobe_bars_on_when_doors_open
    alias: 'Turn on or off wardrobe bars with two wardrobe doors'
    mode: restart
    
    description: >
      Wardrobe bar lights on when open wardrobe
      
    trigger:
      - platform: homeassistant
        id: "start"
        event: start
      - platform: event
        id: "reload"
        event_type: automation_reloaded
      - platform: state
        id: "doors"
        entity_id:
          - binary_sensor.master_bedroom_wardrobe_door_1
          - binary_sensor.master_bedroom_wardrobe_door_2
        to: 'on'
        
    condition:
      - alias: Check Sarah is not asleep
        condition: state
        entity_id: switch.sarah_is_asleep
        state: 'off'
      - alias: Check Bruce is not asleep
        condition: state
        entity_id: switch.bruce_is_asleep
        state: 'off'
        
    action:
      - choose:
          - alias: lights off, door opened
            conditions: 
              - condition: trigger
                id: "doors"
              - condition: state
                entity_id: light.master_bedroom_wardrobe_bars
                state: 'off'
            sequence:
              - alias: Turn on Lights
                service: light.turn_on
                target:
                  entity_id: light.master_bedroom_wardrobe_bars
              - alias: wait for doors to close
                wait_for_trigger:
                  - platform: template
                    value_template: "{{ is_state('binary_sensor.master_bedroom_wardrobe_door_1','off') and is_state('binary_sensor.master_bedroom_wardrobe_door_2','off') }}"
                timeout: 00:10:00
                continue_on_timeout: true      
              - alias: turn off lights
                service: light.turn_off
                target:
                  entity_id: light.master_bedroom_wardrobe_bars

          - conditions: 
              - alias: lights on, door opened          
                condition: trigger
                id: "doors"
              - condition: state
                entity_id: light.master_bedroom_wardrobe_bars
                state: 'on'
            sequence:
              - alias: wait for door to close
                wait_for_trigger:
                  - platform: template
                    value_template: "{{ is_state('binary_sensor.master_bedroom_wardrobe_door_1','off') and is_state('binary_sensor.master_bedroom_wardrobe_door_2','off') }}"
                timeout: 00:10:00
                  
        default:
          - alias: turn light off
            service: light.turn_off
            target:
              entity_id: light.master_bedroom_wardrobe_bars
      