sensor:
  - platform: statistics
    unique_id: statistics_mb_co2_max
    entity_id: sensor.master_bedroom_environment_co2
    sampling_size: 250
    precision: 0
    name: Master Bedroom Environment CO2 Max
    state_characteristic: value_max    
    max_age:
      hours: 24