automation:
  - id: paddy_enable_charge_when_below_set_price
    alias: 'Paddy Enable Charge When Below Set Price'
    
    description: >
      Switch on automation when price changed
      
    trigger:
      - platform: state
        entity_id: input_number.paddy_charge_below_x_pence
        
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.charge_paddy_when_below_set_price
