automation:
  - id: movement_in_house_noone_home
    alias: Someone is in the house, but noone home
    mode: single
    
    description: >
      Movement in the house, noone home   

    trigger:
      - platform: state
        id: 'motion'
        entity_id: 
          - binary_sensor.lounge_motion
          - binary_sensor.landing_motion
          - binary_sensor.studio_motion          
          - binary_sensor.back_door
          - binary_sensor.front_door
          - binary_sensor.kitchen_motion
          - binary_sensor.conservatory_door
          - binary_sensor.back_gate_door
          - binary_sensor.under_stairs_sensor_motion
          - binary_sensor.under_stairs_door
          - binary_sensor.master_bedroom_door
          - binary_sensor.kates_bedroom_door
          - binary_sensor.sophies_bedroom_door
          - binary_sensor.lounge_door
          - binary_sensor.kitchen_door
          - binary_sensor.bar_door
        to: 'on'
        
    condition:
      - condition: state
        entity_id: group.someone_home
        state: not_home
        
    action:
      service: input_boolean.turn_on
      target:
        entity_id: input_boolean.house_motion_detected  