automation:
  - id: show_alarm_armed_disarmed_in_morning
    alias: Show if alarm armed or disatmed in morning
    mode: restart
    
    description: >
      Use stairs lightstrip to show alarm status

    trigger:
      - platform: state
        id: 'kitchen'
        entity_id:            
          - binary_sensor.kitchen_door   
          - binary_sensor.kitchen
        to: 'on'    
      - platform: state
        id: 'lounge'
        entity_id:            
          - binary_sensor.lounge_door
          - binary_sensor.lounge         
      - platform: state
        id: 'landing'
        entity_id:            
          - binary_sensor.landing
          - binary_sensor.landing_motion
        to: 'on'
      - platform: state
        id: 'disarmed'
        entity_id: alarm_control_panel.texecom
        to: 'disarmed'
#      - platform: state
#        id: 'armed_night'
#        entity_id: alarm_control_panel.texecom
#        to: 'armed_night'        
        
    condition:
      - condition: state
        entity_id: input_boolean.someone_has_been_downstairs
        state: 'off'
      - condition: time
        after: '05:45:00'
        
    action:
      - choose:
            # Kitchen Door or motion and alarm armed Night
          - conditions: 
              - condition: trigger
                id: 'kitchen'
              - condition: state
                entity_id: alarm_control_panel.texecom
                state: 'armed_night'
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.hall_stairs_lightstrip
                data:
                  brightness: 255
                  rgb_color: [255,0,0]
              - service: light.turn_on
                target:
                  entity_id: light.kitchen_1
                data:
                  brightness: 255
                  rgb_color: [255,0,0]       
            # Lounge Door or motion and alarm armed Night                
          - conditions: 
              - condition: trigger
                id: 'lounge'
              - condition: state
                entity_id: alarm_control_panel.texecom
                state: 'armed_night'
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.hall_stairs_lightstrip
                data:
                  brightness: 255
                  rgb_color: [255,0,0]
              - service: light.turn_on
                target:
                  entity_id: light.lounge_right
                data:
                  brightness: 255
                  rgb_color: [255,0,0]       
            # Lounge/Kitchen Door or motion                      
          - conditions: 
              - or:
                  - condition: trigger
                    id: 'kitchen'
                  - condition: trigger
                    id: 'lounge'                    
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.hall_stairs_lightstrip
                data:
                  brightness: 50
                  rgb_color: [255,206,121]
                  transition: 1
              - service: light.turn_off
                target:
                  entity_id: 
                    - light.lounge_right
                    - light.kitchen_1
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.someone_has_been_downstairs   
                  
          - conditions: 
              - condition: state
                entity_id: alarm_control_panel.texecom
                state: 'armed_night'
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.hall_stairs_lightstrip
                data:
                  brightness: 128
                  rgb_color: [255,0,0]
                  transition: 3
                  
          - conditions: 
              - condition: state
                entity_id: alarm_control_panel.texecom
                state: 'disarmed'
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.hall_stairs_lightstrip
                data:
                  brightness: 128
                  rgb_color: [0,255,0]
                  transition: 3    
