automation:
  - id: movement_in_shed_or_garage
    alias: 'Someone is in the Shed or Garage'
    mode: single
    
    description: >-
      movement in the shed or garage

    trigger:
      - platform: state
        id: "movement"
        entity_id: binary_sensor.shed_garage
        to: 'on'

    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.garage_motion_detected