automation:
  - id: hottub_turn_on_scheduled_when_time_changed
    alias: 'HotTub Turn on scheduled when time changed'
    
    description: >
      Schedule on or off based on time change
      
    trigger:
      - platform: state
        entity_id: input_datetime.hottub_ready_by
        
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.hottub_scheduled