automation:
  - id: reset_radiators_to_auto
    alias: 'Reset Radiators to Auto Overnight'
    mode: single
    
    description: >
      Reset radiators to auto
      
    trigger:
      - platform: time
        id: "2300"
        at: "23:00:00"
      - platform: homeassistant
        id: "start"
        event: start
      - platform: event
        id: "reload"
        event_type: automation_reloaded  
        
    action:
      - service: climate.set_hvac_mode
        target:
          entity_id: 
            - climate.bar_rad
            - climate.conservatory_rad
            - climate.downstairs_loo_rad
            - climate.drum_room_rad
            - climate.hall_rad
            - climate.kitchen_rad
            - climate.kitchen_tall_rad      
            - climate.landing_1_rad
            - climate.landing_2_rad
            - climate.lounge_bay_rad
            - climate.lounge_rad
            - climate.master_bedroom_rad      
        data:            
          hvac_mode: auto
      - service: climate.set_hvac_mode
        target: 
          entity_id: 
            - climate.kates_bedroom_rad
            - climate.kates_bathroom_rad
        data:
          hvac_mode: "{% if is_state('calendar.kate_yarbury','on') %}auto{% else %}off{% endif %}"
      - service: climate.set_hvac_mode
        target: 
          entity_id: climate.sophies_bedroom_rad
        data:
          hvac_mode: "{% if is_state('calendar.sophie_yarbury','on') %}auto{% else %}off{% endif %}"          
      - service: climate.set_hvac_mode
        target: 
          entity_id: climate.guest_bedroom_rad
        data:
          hvac_mode: "{% if is_state('calendar.guest_yarbury','on') %}auto{% else %}off{% endif %}"          
      
  