automation:
  - id: set_sophies_radiators
    alias: 'Set sophies radiators'

    description: >
      set Sophies rads from calendar
      
    trigger:
      - platform: time
        at: 
          - '06:00:00'
          - '13:00:00'
      - platform: homeassistant
        id: "start"
        event: start
      - platform: event
        id: "reload"
        event_type: automation_reloaded  
        
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: calendar.sophie_yarbury
                state: 'on'          
            sequence:
              - service: climate.set_hvac_mode
                target: 
                  entity_id: climate.sophies_bedroom_rad
                data:
                  hvac_mode: 'auto'
          - conditions: 
              - condition: time
                after: '12:00:00'
            sequence:
              - service: climate.set_hvac_mode
                target: 
                  entity_id: climate.sophies_bedroom_rad
                data:
                  hvac_mode: 'off'                  
                  
                  