automation:
  - id: turn_on_heating
    alias: Turn on heating
    
    description: >
      turn on heating
      
    trigger:
      - platform: event
        id: "ios notification"
        event_type: ios.notification_action_fired
        event_data:
          actionName: TURN_ON_HEATING
      - platform: event
        id: "ios action"      
        event_type: ios.action_fired
        event_data:
          actionName: 'heating_on'
          
    action:
      - service: water_heater.set_operation_mode
        target:
          entity_id: water_heater.hot_water
        data:
          operation_mode: eco
      - service: climate.set_hvac_mode
        target: 
          entity_id:
            - climate.heating
            - climate.kitchen_tall_rad
            - climate.bar_rad
            - climate.drum_room_rad
            - climate.landing_1_rad
            - climate.master_bedroom_rad
            - climate.downstairs_loo_rad
            - climate.landing_2_rad
            - climate.hall_rad
            - climate.lounge_bay_rad
            - climate.lounge_rad
            - climate.conservatory_rad
            - climate.kitchen_rad
        data:
          hvac_mode: 'auto'
      - service: climate.set_hvac_mode
        target: 
          entity_id: 
            - climate.kates_bedroom_rad
            - climate.kates_bathroom_rad
        data:
          hvac_mode: "{% if is_state('calendar.kate_yarbury','on') %}auto{% else %}off{% endif %}"
      - service: climate.set_hvac_mode
        target: 
          entity_id: climate.sophies_bedroom_rad
        data:
          hvac_mode: "{% if is_state('calendar.sophie_yarbury','on') %}auto{% else %}off{% endif %}"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.away_heating_off