automation:
  - id: set_guests_radiators
    alias: 'Set guests radiators'
    
    description: >
      set Guests rads from calendar
    
    trigger:
      - platform: time
        id: "time"
        at: 
          - '06:00:00'
          - '13:00:00'
      - platform: homeassistant
        id: "start"
        event: start
      - platform: event
        id: "reload"
        event_type: automation_reloaded  
        
    action:
      - choose:
          - conditions: 
              - condition: state
                entity_id: calendar.guest_yarbury
                state: 'on'
            sequence:
              - service: climate.set_hvac_mode
                target: 
                  entity_id: climate.guest_bedroom_rad
                data:
                  hvac_mode: 'auto'
          - conditions: 
              - condition: time
                after: '12:00:00'
            sequence:
              - service: climate.set_hvac_mode
                target: 
                  entity_id: climate.guest_bedroom_rad
                data:
                  hvac_mode: 'off'    