automation:
  - id: delete_cam_files_over_a_week
    alias: 'Delete Cam Files older than a week'
    
    description: >
      Delete old cam files based on date stamp
      
    trigger:
      - platform: time
        id: "410"
        at: '04:10:00'            
        
    action:
      - service: delete.files_in_folder
        data:
          folder: /config/www/cam_snaps
          time: 604800
          only_extensions: .mp4
          scan_subfolders: false
          remove_subfolders: false
      - service: delete.files_in_folder
        data:
          folder: /config/platerecogniser
          time: 604800
          only_extensions: .png
          scan_subfolders: false
          remove_subfolders: false          
