# Double Take
# Learn more at https://github.com/jakowenko/double-take/#configuration

mqtt:
  host: 192.168.11.124
  username: !secret mqtt_username
  password: !secret mqtt_password
  
detectors:
  compreface:
    url: 192.168.11.124:8000
    key: !secret compreface_key  